env:
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=1.22 GHCVER=7.10.3
 - CABALVER=1.24 GHCVER=8.0.1

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy-1.19.4 alex-3.1.3 libgtk-3-dev libwebkitgtk-3.0-dev
 - travis_retry wget "http://mirrors.kernel.org/ubuntu/pool/universe/z/zeromq3/libzmq3_4.0.4+dfsg-2_amd64.deb"
 - travis_retry wget "http://mirrors.kernel.org/ubuntu/pool/universe/z/zeromq3/libzmq3-dev_4.0.4+dfsg-2_amd64.deb"
 - travis_retry sudo dpkg -i libzmq3_4.0.4+dfsg-2_amd64.deb
 - travis_retry sudo dpkg -i libzmq3-dev_4.0.4+dfsg-2_amd64.deb
 - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install gtk2hs-buildtools
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
 - cabal build
 - cabal test
 - cabal check
 - cabal sdist

# Check that the resulting source distribution can be built & installed.
# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
# `cabal install --force-reinstalls dist/*-*.tar.gz`
 - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
